### ISSUE TITLE
Doesn't work in matrix

### ISSUE THREAD

**Issue by havardlj** [nthmedia/entry-gps-coordinates#16]
This plugin doesn't seem to work as a matrix-field (several instances on the same page). I am able to work around this, but thought that I would point it out.

**Comment by niektenhoopen** [comment]
Hi @havardlj! That is something that I would need to check out. I developed this for a scenario where an Entry has one location. I would then connect the Entry in a matrix block instead of using the location field in a matrix block. I am currently very busy but I will definitely put it on my to-do list. Hope I gave you potential work-around
